version: '3.8'

services:
  mcp-ble-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
    privileged: true  # Required for BLE access
    devices:
      - /dev/bluetooth:/dev/bluetooth
    restart: unless-stopped 