#!/bin/sh

# Redirect output to stderr
exec 1>&2

# Get list of staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "\nValidating Javascript:\n"

# Check for eslint
if [ ! -f "./node_modules/.bin/eslint" ]; then
  echo "\t\033[41mPlease install ESlint using: npm install eslint --save-dev\033[0m"
  exit 1
fi

for FILE in $STAGED_FILES
do
  ./node_modules/.bin/eslint "$FILE"

  if [[ "$?" == 0 ]]; then
    echo "\t\033[32mESLint Passed: $FILE\033[0m"
  else
    echo "\t\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi
done

echo "\nJavascript validation completed!\n"

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

# Run only stable tests
echo "Running stable tests..."
CI_CRITICAL_ONLY=true npm run test:stable

if [[ "$?" == 1 ]]; then
  echo "\033[41mCOMMIT FAILED:\033[0m Stable tests must pass before commit!\n"
  exit 1
fi

exit 0
