name: MCP BLE Server CI/CD

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

permissions:
  contents: read
  actions: read
  checks: write
  id-token: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm run test:stable
        env:
          CI: true
          CI_CRITICAL_ONLY: true
          
      - name: Upload coverage reports
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: |
          npm run lint:fix
          npm run lint
        
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run security audit
        run: npm audit
        
      - name: Run dependency check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'MCP BLE Server'
          path: '.'
          format: 'HTML'
          out: 'reports'
          
  build:
    name: Build
    needs: [test, lint, security]
    runs-on: ubuntu-latest
    outputs:
      artifact_name: build-artifacts
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: |
          # Run the build script with detailed output
          npm run build --verbose

          # Debug output
          echo "Build completed. Checking dist directory structure:"
          ls -la
          echo "\nContents of dist directory:"
          ls -la dist/
          echo "\nChecking package.json in dist:"
          cat dist/package.json
          echo "\nChecking node_modules in dist:"
          ls -la dist/node_modules || echo "No node_modules directory found in dist"

      - name: Run build verification
        run: npm run build:verify

      - name: Create artifact manifest
        run: |
          mkdir -p artifacts
          {
            echo "MCP BLE Server Build Artifact"
            echo "Build Date: $(date)"
            echo "Git Commit: ${{ github.sha }}"
            echo "Build Number: ${{ github.run_number }}"
            echo "Node.js Version: $(node --version)"
            echo "NPM Version: $(npm --version)"
            echo -e "\nEnvironment:"
            env | grep -v "SECRET\|TOKEN\|PASSWORD\|KEY"
            echo -e "\nContents:"
            ls -laR dist/
          } > artifacts/manifest.txt

      - name: Prepare artifacts
        run: |
          # Create a tarball of the dist directory
          tar -czf artifacts/dist.tar.gz dist/

          # Create SHA256 checksum
          sha256sum artifacts/dist.tar.gz > artifacts/dist.tar.gz.sha256

          # Verify the tarball
          tar -tzf artifacts/dist.tar.gz > /dev/null || (echo "Invalid tarball" && exit 1)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build.outputs.artifact_name }}
          path: artifacts/
          if-no-files-found: error
          retention-days: 7

      - name: Upload dist directory
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build.outputs.artifact_name }}-dist
          path: dist/
          if-no-files-found: error
          retention-days: 7
          
  deploy-staging:
    name: Deploy to Staging
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: ${{ steps.deploy.outputs.alb_dns_name }}
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact_name }}-dist
          path: dist

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: artifacts

      - name: Verify downloaded artifacts
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "\nContents of artifacts directory:"
          ls -la artifacts/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      - name: Terraform Init
        working-directory: infrastructure/staging
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        id: plan
        working-directory: infrastructure/staging
        run: |
          terraform plan \
            -var-file="terraform.tfvars" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -out=tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        id: deploy
        working-directory: infrastructure/staging
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          terraform apply -auto-approve tfplan
          echo "alb_dns_name=$(terraform output -raw alb_dns_name)" >> $GITHUB_OUTPUT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan-staging
          path: infrastructure/staging/tfplan
          if-no-files-found: error
          retention-days: 7

      - name: Deploy Application
        run: |
          # Verify dist directory contents
          echo "Verifying dist directory contents..."
          ls -la dist/
          
          # Deploy application using AWS CLI
          echo "Deploying application to ECS..."
          aws ecs update-service \
            --cluster staging-cluster \
            --service mcp-ble-server \
            --force-new-deployment \
            --region us-east-1
          
          # Wait for service to stabilize
          echo "Waiting for service to stabilize..."
          aws ecs wait services-stable \
            --cluster staging-cluster \
            --services mcp-ble-server \
            --region us-east-1
          
          echo "Deployment completed successfully"

      - name: Verify Deployment
        run: |
          # Get the latest task definition
          TASK_DEF=$(aws ecs describe-services \
            --cluster staging-cluster \
            --services mcp-ble-server \
            --region us-east-1 \
            --query 'services[0].taskDefinition' \
            --output text)
          
          # Check task status
          aws ecs describe-task-definition \
            --task-definition $TASK_DEF \
            --region us-east-1
          
          echo "Deployment verification completed" 